### ISSUE TITLE
Do I need to normalize the .h5ad files downloaded from Human Kidney Cell Atlas?

### ISSUE THREAD

**Issue by genecell** [bjstewart1/kidney_sc_immune#2]
Hi,

I don't know whether the .h5ad data downloaded from the Human Kidney Cell Atlas website (https://www.kidneycellatlas.org) is raw data or processed data. I processed the .h5ad data as raw data, including the following processing:

`sc.pp.normalize_total(adata, target_sum=1e4)`
`sc.pp.log1p(adata)`

I did not find instructions or notes about whether the .h5ad data is raw data or not, so I think it's better for me to ask here.
Thank you!

Best regards,
Min

**Comment by bjstewart1** [comment]
This is normalised data.
If you would like raw counts please email me bs567@cam.ac.uk
